export { default as StepPhoneEmail } from './StepPhoneEmail/StepPhoneEmail'
export { default as StepOtp } from './StepOtp/StepOtp'
export { default as StepName } from './StepName/StepName'
export { default as StepAvatar } from './StepAvatar/StepAvatar'
export { default as StepUsername } from './StepUsername/StepUsername'