export { default as Home } from './Home/Home'
export { default as Register } from './Register/Register'
export { default as Login } from './Login/Login'
export { default as Authenticate } from './Authenticate/Authenticate'
export { default as Activate } from './Activate/Activate'